### PR TITLE
Fix the issue where close button of the modal/popup screen is not visible on some screen sizes

### LINKED ISSUE #6: The close button in the Linked Commons is not visible.
## Describe the bug
The close button on the  [Linked Common](http://dataviz.creativecommons.engineering/) website which should appear in the popup screen after clicking on a node (having some license information) is not visible on the deployed version. So once the user has clicked a node he is unable to close the details/ piechart modal of the node.

## To Reproduce
1. Go to [Linked Common website](http://dataviz.creativecommons.engineering/)
2. Click on 'any node'
3. If the popup window says no information for the given license. Then close the node and select some other node with some information.
4. Error 'There is no close button to go back to the starting screen'.

## Expected behavior
The close button should be visible to the user so he/she can go back to the graph screen.

## Screenshots
ice_screenshot_20200224-231053
Screenshot on chrome browser with no close button.
ice_screenshot_20200224-231021
Screenshot on firefox with no close button.

## Desktop 
 - OS: windows 10
 - Browser Chrome, Firefox
 - Version Chrome v79.0, Firefox 73.0.1

## Additional context
I will like to solve this issue. So please assign me this issue.

### PR DESCRIPTION
**Pull request by BharatNischal**
Fixes #6 

## Description
I had  added the **overflow-y : scroll** property on the modal so that the close button is visible under all screen sizes and under all browsers in case of any overflow.
Added a new functionality where clicking outside the popup screen closes it.

## Screenshots

**Previous Version**
ice_screenshot_20200224-231053

**New Version**
ice_screenshot_20200228-010244

## Developer Certificate of Origin
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by BharatNischal** [comment]
@kgodey please review this PR. If there is anything else I can work to solve this issue please let me know.

**Comment by kgodey** [comment]
I'll leave it to @soccerdroid or @mathemancer to review.

**Comment by soccerdroid** [comment]
Do you think the horizontal scroll bar could be removed? It seems to have no functionality.

**Comment by BharatNischal** [comment]
> Do you think the horizontal scroll bar could be removed? It seems to have no functionality.
@soccerdroid 
yes I will remove it
Should I send you a new PR?
Is everything else alright?

**Comment by soccerdroid** [comment]
The padding is set for aesthetic, so we don't have text too close to the borders. Like you mentioned, it follows material design. Why do think the padding was unnecessary?

**Comment by soccerdroid** [comment]
> > Do you think the horizontal scroll bar could be removed? It seems to have no functionality.
> > @soccerdroid
> > yes I will remove it
> > Should I send you a new PR?
> > Is everything else alright?

You can do a git commit --amend and force push your changes, they will be reflected in this same PR

**Comment by soccerdroid** [comment]
Oh and please add the Developer Certificate of Origin in your PR description, I just realized it was not included.

**Comment by BharatNischal** [comment]
> The padding is set for aesthetic, so we don't have text too close to the borders. Like you mentioned, it follows material design. Why do think the padding was unnecessary?
I thought that was unnecessary in the sense that they were causing overflow in my device (before I used the overflow property). But you are right I think i should revert it back.
Thanks @soccerdroid  for the advice.
I will make changes as directed by you.

**Comment by BharatNischal** [comment]
@soccerdroid I had made the necessary changes directed by you and had included the Developer Certificate Of Origin.  Please have a look again

**Comment by BharatNischal** [comment]
@soccerdroid is the PR now good to merge? Or do I need to make any other changes?

**Review by soccerdroid — APPROVED** [review]

**Review by mathemancer — APPROVED** [review]

**Comment by BharatNischal** [comment]
@kgodey the PR has been approved. Can you please merge it now?

**Pull request merged**
