### PR TITLE
New font-size logic

### LINKED ISSUE #11: Reducing the complexity and computational time with new logic
## Describe the bug
Under the nodeCanvasObject method of the Force graph there is a logic which adjusted the font size of text such that the font size is maximum without overflowing out of the node (shown in screenshot). This logic uses a do while loop. However a constant time solution exists (without any loop) Since the method is called for each node , using the constant time solution can reduce the computational time.
Also the font size calculated from current algorithm is not so accurate as compared to the proposed logic(As shown in screenshot).

## Expected behavior
A simple, fast and more accurate constant time solution is possible which can reduce the computational time.

## Screenshots
**Screenshot of the current logic**
ice_screenshot_20200226-211934

**Screenshot of website with the current logic implementation**(see the font size of coveralia)
ice_screenshot_20200225-182415

**Screenshot of website with the proposed logic run locally on my machine**(see the font size of coveralia)
ice_screenshot_20200225-182449

## Desktop (please complete the following information)
 - OS: windows 10
 - Browser chrome
 - Version 80.0

## Extra Info
I had already tested the new logic locally so I request you to please assign the issue to me

### PR DESCRIPTION
**Pull request by BharatNischal**
Fixes #11 

## Description

Under the nodeCanvasObject method of the Force graph there is a logic which adjusted the font size of text such that the font size is maximum without overflowing out of the node  This logic previously uses a do while loop. However the new logic now first calculate the size of text by taking font-size as 1px and then divides the diameter of node with the size of text to calculate the no. of times the font size need to shrink/grow .Thus the new logic will reduce the time as well as fit the text more precisely as shown in the screenshots.

## Screenshots
**Previous version**
ice_screenshot_20200225-182415

**New version**
ice_screenshot_20200306-211045

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by BharatNischal** [comment]
@kgodey @soccerdroid @mathemancer please review this PR

**Comment by soccerdroid** [comment]
Do you think we can have like padding? Because as it is now, the first and last letter of a domain could not fit entirely (see the reddit node in your second screenshot). Or maybe just decrease a little bit the font size after calculating its value.

**Review by soccerdroid — CHANGES_REQUESTED** [review]
Do you think we can have like padding? Because as it is now, the first and last letter of a domain could not fit entirely (see the reddit node in your second screenshot). Or maybe just decrease a little bit the font size after calculating its value.

**Comment by BharatNischal** [comment]
> Do you think we can have like padding? Because as it is now, the first and last letter of a domain could not fit entirely (see the reddit node in your second screenshot). Or maybe just decrease a little bit the font size after calculating its value.

@soccerdroid what about decreasing the font-size by 0-2 px depending upon the node size?
For smaller node sizes don't reduce font size and for larger nodes reduce it by 2px for avg cases reduce by 1px.

**Comment by BharatNischal** [comment]
@soccerdroid  I had tried various values but these works fine for me
`
if(fontsize>3){ //So that fontsize is never 0

            if(node.node_size>70 && node.id.length <=5)
              fontsize -= 5;
            if(node.node_size>70 || node.id.length <=5)
              fontsize  -= 3;
            else
              fontsize--;

          }
`
should I commit these changes? or any other suggestion

**Comment by BharatNischal** [comment]
> @soccerdroid I had tried various values but these works fine for me
> `
> if(fontsize>=5 && node.node_size>70 && node.id.length <=5)
            fontsize -= 5;
          else if(fontsize>=3 && node.node_size>70)
            fontsize -= 3;
          else
            fontsize--;
> ```

@soccerdroid  what you say?

**Review by BharatNischal — COMMENTED** [review]
I had made changes to the fontsize so that it is completely inside the node
ice_screenshot_20200306-211045

**Comment by soccerdroid** [comment]
Hi @BharatNischal ! Could you try to fit this in one commit? Reverting changes should not be a commit, and as there are not a lot of files or code lines that have changed, we could have this enhancement in  a single commit. The output looks good now.

**Comment by BharatNischal** [comment]
> Hi @BharatNischal ! Could you try to fit this in one commit? Reverting changes should not be a commit, and as there are not a lot of files or code lines that have changed, we could have this enhancement in a single commit. The output looks good now.

oh sorry for the extra commits , I realized that I had forgot to make it as a hard revert so it was showing as an extra commit.
Now I have fixed that

**Review by soccerdroid — APPROVED** [review]

**Comment by mathemancer** [comment]
Hey, after this merge, I'm getting a visual glitch on my machine that seems font size related.  @soccerdroid Can you confirm?

image

**Comment by BharatNischal** [comment]
@mathemancer  Can you please tell me in which browser and under what device are you getting this issue? 
Because its working fine in my device.
ice_screenshot_20200318-211819

ice_screenshot_20200318-211938


> Hey, after this merge, I'm getting a visual glitch on my machine that seems font size related. @soccerdroid Can you confirm?
> 
> image

**Comment by mathemancer** [comment]
Here's my UA String:

Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Pull request merged**
